### ISSUE TITLE
Error when using navigateNextCell and navigatePreviousCell

### ISSUE THREAD

**Issue by keroe** [takumisoft68/vscode-markdown-table#13]
Hi,
I really liked the demo of your vs code extension. But it seems like I can't use the navigation commands. I first tried to use the shortcuts `tab` and `shift+tab`, but it didn't work. When I tried to use the command via right click an error occurred. 
Some system information:
```
OS: Ubuntu 18.04
VS Code Version: 1.51.1
```
The error for navigateNextCell:
```
[2020-11-19 11:54:17.112] [exthost] [error] TypeError: Cannot read property 'trim' of undefined
        at splitline (/home/user/.vscode/extensions/takumii.markdowntable-0.4.1/out/markdowntable.js:20:31)
        at MarkdownTable.stringToTableData (/home/user/.vscode/extensions/takumii.markdowntable-0.4.1/out/markdowntable.js:51:26)
        at navigateNextCell (/home/user/.vscode/extensions/takumii.markdowntable-0.4.1/out/extension.js:64:29)
        at /home/user/.vscode/extensions/takumii.markdowntable-0.4.1/out/extension.js:182:9
        at _executeContributedCommand (/snap/code/50/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:699:753)
        at _.$executeContributedCommand (/snap/code/50/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:700:104)
        at g._doInvokeHandler (/snap/code/50/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:876:926)
        at g._invokeHandler (/snap/code/50/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:876:618)
        at g._receiveRequest (/snap/code/50/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:875:252)
        at g._receiveOneMessage (/snap/code/50/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:874:6)
        at /snap/code/50/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:872:136
        at l.fire (/snap/code/50/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:46:67)
        at v.fire (/snap/code/50/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:256:601)
        at /snap/code/50/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:1066:179
        at l.fire (/snap/code/50/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:46:67)
        at v.fire (/snap/code/50/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:256:601)
        at t.PersistentProtocol._receiveMessage (/snap/code/50/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:261:629)
        at /snap/code/50/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:258:708
        at l.fire (/snap/code/50/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:46:67)
        at p.acceptChunk (/snap/code/50/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:253:989)
        at /snap/code/50/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:253:341
        at Socket.t (/snap/code/50/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:263:276)
        at Socket.emit (events.js:223:5)
        at addChunk (_stream_readable.js:309:12)
        at readableAddChunk (_stream_readable.js:290:11)
        at Socket.Readable.push (_stream_readable.js:224:10)
        at Pipe.onStreamRead (internal/stream_base_commons.js:181:23) markdowntable.nextCell
```
The error for navigatePreviousCell:
```
[2020-11-19 11:52:00.915] [exthost] [error] TypeError: Cannot read property 'trim' of undefined
        at splitline (/home/user/.vscode/extensions/takumii.markdowntable-0.4.1/out/markdowntable.js:20:31)
        at MarkdownTable.stringToTableData (/home/user/.vscode/extensions/takumii.markdowntable-0.4.1/out/markdowntable.js:51:26)
        at navigatePrevCell (/home/user/.vscode/extensions/takumii.markdowntable-0.4.1/out/extension.js:156:29)
        at /home/user/.vscode/extensions/takumii.markdowntable-0.4.1/out/extension.js:185:9
        at _executeContributedCommand (/snap/code/50/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:699:753)
        at _.$executeContributedCommand (/snap/code/50/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:700:104)
        at g._doInvokeHandler (/snap/code/50/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:876:926)
        at g._invokeHandler (/snap/code/50/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:876:618)
        at g._receiveRequest (/snap/code/50/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:875:252)
        at g._receiveOneMessage (/snap/code/50/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:874:6)
        at /snap/code/50/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:872:136
        at l.fire (/snap/code/50/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:46:67)
        at v.fire (/snap/code/50/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:256:601)
        at /snap/code/50/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:1066:179
        at l.fire (/snap/code/50/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:46:67)
        at v.fire (/snap/code/50/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:256:601)
        at t.PersistentProtocol._receiveMessage (/snap/code/50/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:261:629)
        at /snap/code/50/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:258:708
        at l.fire (/snap/code/50/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:46:67)
        at p.acceptChunk (/snap/code/50/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:253:989)
        at /snap/code/50/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:253:341
        at Socket.t (/snap/code/50/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:263:276)
        at Socket.emit (events.js:223:5)
        at addChunk (_stream_readable.js:309:12)
        at readableAddChunk (_stream_readable.js:290:11)
        at Socket.Readable.push (_stream_readable.js:224:10)
        at Pipe.onStreamRead (internal/stream_base_commons.js:181:23) markdowntable.prevCell
```

Is there something my system is missing?
If you need more information about my system I'm happy to provide more.
Thanks in advance

**Comment by keroe** [comment]
Nevermind. My table was not in the right format. It was an user error not a programming error.
