### ISSUE TITLE
[BUG] Exception Trace in console becuase of undefined editor

### ISSUE THREAD

**Issue by frudolph77** [takumisoft68/vscode-markdown-table#44]
Hello,

I've seen the trace below in the console log.

Every time you 'request' the editor from `vscode.window.activeTextEditor` you should check if it is not `undefined`.  

Anyway, thanks for your extension.

Kind regards
Frank

Trace:

```
mainThreadExtensionService.ts:76 TypeError: Cannot read properties of undefined (reading 'document')
	at Object.updateContextKey (vscode-file://vscode-app/home/fru/.vscode-insiders/extensions/takumii.markdowntable-0.9.1/out/commands.js:12:24)
	at vscode-file://vscode-app/home/fru/.vscode-insiders/extensions/takumii.markdowntable-0.9.1/out/extension.js:21:89
	at u.invoke (vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:58:145)
	at w.fire (vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:58:1856)
	at vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:86:66000
	at u.invoke (vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:58:145)
	at w.fire (vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:58:1856)
	at _.acceptDocumentsAndEditorsDelta (vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:85:75835)
	at _.$acceptDocumentsAndEditorsDelta (vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:85:73924)
	at i._doInvokeHandler (vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:89:13826)
	at i._invokeHandler (vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:89:13510)
	at i._receiveRequest (vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:89:12171)
	at i._receiveOneMessage (vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:89:10841)
	at vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:89:8947
	at u.invoke (vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:58:145)
	at w.fire (vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:58:1856)
	at d.fire (vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:66:19030)
	at vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:104:34269
	at u.invoke (vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:58:145)
	at w.fire (vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:58:1856)
	at d.fire (vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:66:19030)
	at o._receiveMessage (vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:66:23611)
	at vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:66:21145
	at u.invoke (vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:58:145)
	at w.fire (vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:58:1856)
	at w.acceptChunk (vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:66:15861)
	at vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:66:14991
	at Socket.P (vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:104:13797)
	at Socket.emit (node:events:390:28)
	at addChunk (node:internal/streams/readable:315:12)
	at readableAddChunk (node:internal/streams/readable:289:9)
	at Socket.Readable.push (node:internal/streams/readable:228:10)
	at Pipe.onStreamRead (node:internal/stream_base_commons:199:23)
```

**Comment by takumisoft68** [comment]
@frudolph77 Thanks to your feedback!
